//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbentity.toolstrackingsystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_OutBackStore
    {
        public long OutBackStoreID { get; set; }
        public string ToolCode { get; set; }
        public string ToolName { get; set; }
        public string OutStoreTime { get; set; }
        public string PersonCode { get; set; }
        public string PersonName { get; set; }
        public string UserTimeInfo { get; set; }
        public string IsBack { get; set; }
        public string BackTime { get; set; }
        public string BackPesonCode { get; set; }
        public string BackPersonName { get; set; }
        public string outdescribes { get; set; }
        public string backdescribes { get; set; }
        public string OptionPerson { get; set; }
        public string IsCredit { get; set; }
    }
}
