//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbentity.toolstrackingsystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ToolRepairRecord
    {
        public long ID { get; set; }
        public string TypeName { get; set; }
        public string ChildTypeName { get; set; }
        public string PackCode { get; set; }
        public string PackName { get; set; }
        public string ToolCode { get; set; }
        public string ToolName { get; set; }
        public System.DateTime RepairedTime { get; set; }
        public string RepairedPerson { get; set; }
        public Nullable<System.DateTime> ReturnedTime { get; set; }
        public string ReturnedPerson { get; set; }
        public Nullable<System.DateTime> ReceivedTime { get; set; }
        public string ReceivedPerson { get; set; }
        public Nullable<System.DateTime> ReceivedBackTime { get; set; }
        public string ReceivedBackPerson { get; set; }
        public Nullable<int> ToolStatus { get; set; }
    }
}
