//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbentity.toolstrackingsystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ToolRepairRecord
    {
        public int Id { get; set; }
        public string TypeName { get; set; }
        public string ChildTypeName { get; set; }
        public string PackCode { get; set; }
        public string PackName { get; set; }
        public string ToolCode { get; set; }
        public string ToolName { get; set; }
        public Nullable<System.DateTime> ToRepairedTime { get; set; }
        public string ToRepairedPerCode { get; set; }
        public string ToRepairedPerName { get; set; }
        public Nullable<System.DateTime> ReceiveTime { get; set; }
        public string ReceivePerCode { get; set; }
        public string ReceivePerName { get; set; }
        public Nullable<System.DateTime> HandleTime { get; set; }
        public string HandlePerCode { get; set; }
        public string HandlePerName { get; set; }
        public Nullable<System.DateTime> PullTime { get; set; }
        public string PullPerCode { get; set; }
        public string PullPerName { get; set; }
        public string ToRepairMemo { get; set; }
        public string ScrapMemo { get; set; }
        public int ToolStatus { get; set; }
    }
}
