//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbentity.toolstrackingsystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ToolInfo
    {
        public long ToolID { get; set; }
        public string TypeName { get; set; }
        public string ChildTypeName { get; set; }
        public string PackCode { get; set; }
        public string PackName { get; set; }
        public string CarGroupInfo { get; set; }
        public string ToolCode { get; set; }
        public string ToolName { get; set; }
        public string Models { get; set; }
        public string Location { get; set; }
        public string Remarks { get; set; }
        public string CheckTime { get; set; }
        public string IsActive { get; set; }
        public string OptionPerson { get; set; }
        public string IsBack { get; set; }
    }
}
